'use client';

import { useState } from 'react';

interface AISummaryProps {
  content: string;
}

export default function AISummary({ content }: AISummaryProps) {
  const [isOpen, setIsOpen] = useState(false);

  // Mock AI summary logic - in production this would be a server-side pre-generated field
  const summaryPoints = [
    "Investigation reveals critical gaps in local policy implementation.",
    "Election Commissioner emphasizes zero-tolerance for administrative interference.",
    "Community leaders call for more transparent reporting and civic engagement.",
    "Analysis suggest significant shifts in voter sentiment across North Bengal."
  ];

  return (
    <div className="mb-12 bg-gray-50 rounded-[32px] overflow-hidden border border-gray-100 transition-all duration-500">
      <button 
        onClick={() => setIsOpen(!isOpen)}
        className="w-full px-8 py-6 flex items-center justify-between group text-left"
      >
        <div className="flex items-center gap-4">
          <div className="w-10 h-10 bg-primary/10 rounded-full flex items-center justify-center text-primary">
            <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 24 24">
              <path d="M12 2L4.5 20.29l.71.71L12 18l6.79 3 .71-.71L12 2z" />
            </svg>
          </div>
          <div>
            <h3 className="text-sm font-black uppercase tracking-widest text-gray-950">AI Summary</h3>
            <p className="text-[10px] text-gray-500 font-bold uppercase tracking-widest">Powered by NTT Intelligence</p>
          </div>
        </div>
        <div className={`transform transition-transform duration-300 ${isOpen ? 'rotate-180' : ''}`}>
          <svg className="w-5 h-5 text-gray-400 group-hover:text-primary" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M19 9l-7 7-7-7" />
          </svg>
        </div>
      </button>

      {isOpen && (
        <div className="px-8 pb-8 animate-in fade-in slide-in-from-top-2 duration-500">
          <div className="h-px bg-gray-200 mb-8" />
          <ul className="space-y-4">
            {summaryPoints.map((point, i) => (
              <li key={i} className="flex gap-4 text-gray-700 leading-relaxed text-lg">
                <span className="text-primary font-black mt-1.5">•</span>
                <span>{point}</span>
              </li>
            ))}
          </ul>
          <div className="mt-8 p-4 bg-white/50 rounded-2xl border border-gray-100 text-[10px] text-gray-400 font-bold uppercase tracking-widest text-center">
            This summary is generated by AI to help you get the gist quickly. Read the full story below for the truth.
          </div>
        </div>
      )}
    </div>
  );
}
